// frontend/dashboard34/components/ava-assistant.tsx
"use client"

import type * as React from "react"
import { useState } from "react"
import { Bot, Maximize2, Minimize2, Send, X } from "lucide-react"

import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Card, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { ScrollArea } from "@/components/ui/scroll-area"
import { cn } from "@/lib/utils"

interface AvaAssistantProps {
  className?: string
}

type Message = {
  id: string
  content: string
  sender: "user" | "assistant"
  timestamp: Date
}

export function AvaAssistant({ className }: AvaAssistantProps) {
  const [isOpen, setIsOpen] = useState(false)
  const [isExpanded, setIsExpanded] = useState(false)
  const [input, setInput] = useState("")
  const [messages, setMessages] = useState<Message[]>([
    {
      id: "welcome",
      content: "Hello! I'm AVA, Artifact Virtual's Assistant. How can I help you?",
      sender: "assistant",
      timestamp: new Date(),
    },
  ])

  const toggleOpen = () => setIsOpen(!isOpen)
  const toggleExpand = () => setIsExpanded(!isExpanded)

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault()

    if (input.trim()) {
      // Add user message
      const userMessage: Message = {
        id: `user-${Date.now()}`,
        content: input,
        sender: "user",
        timestamp: new Date(),
      }

      setMessages((prev) => [...prev, userMessage])
      setInput("")

      // Simulate assistant response (in a real app, you'd call your LLM API here)
      setTimeout(() => {
        const assistantMessage: Message = {
          id: `assistant-${Date.now()}`,
          content:
            "I'm AVA, your virtual assistant. I can help you navigate the Artifact Virtual platform, manage your projects, and answer questions about AI, blockchain, and quantum computing.",
          sender: "assistant",
          timestamp: new Date(),
        }
        setMessages((prev) => [...prev, assistantMessage])
      }, 1000)
    }
  }

  return (
    <div className={cn("fixed bottom-4 right-4 z-50", className)}>
      {/* Floating Button */}
      {!isOpen && (
        <button
          className="flex h-14 w-14 items-center justify-center rounded-full bg-primary text-primary-foreground shadow-lg hover:bg-primary/90 animate-pulse-glow"
          onClick={toggleOpen}
        >
          <Bot className="h-6 w-6" />
        </button>
      )}

      {/* Chat Interface */}
      {isOpen && (
        <div
          className={cn(
            "flex flex-col bg-background rounded-lg border shadow-lg card-hover",
            isExpanded ? "fixed bottom-4 right-4 top-4 left-4 md:left-auto md:w-[600px]" : "w-[350px] h-[500px]",
          )}
        >
          <Card className="flex flex-col h-full border-0 rounded-lg">
            <CardHeader className="border-b px-4 py-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary">
                    <Bot className="h-4 w-4 text-primary-foreground" />
                  </div>
                  <div>
                    <CardTitle className="text-lg gradient-text">AVA</CardTitle>
                    <CardDescription className="text-xs">Artifact Virtual Assistant</CardDescription>
                  </div>
                </div>
                <div className="flex gap-1">
                  <Button variant="ghost" size="icon" className="h-8 w-8" onClick={toggleExpand}>
                    {isExpanded ? <Minimize2 className="h-4 w-4" /> : <Maximize2 className="h-4 w-4" />}
                    <span className="sr-only">{isExpanded ? "Minimize" : "Maximize"}</span>
                  </Button>
                  <Button variant="ghost" size="icon" className="h-8 w-8" onClick={toggleOpen}>
                    <X className="h-4 w-4" />
                    <span className="sr-only">Close</span>
                  </Button>
                </div>
              </div>
            </CardHeader>
            <ScrollArea className="flex-1 p-4">
              <div className="flex flex-col gap-4">
                {messages.map((message) => (
                  <div
                    key={message.id}
                    className={cn(
                      "flex w-max max-w-[80%] flex-col gap-2 rounded-lg px-3 py-2 text-sm",
                      message.sender === "user" ? "ml-auto bg-primary text-primary-foreground" : "bg-muted",
                    )}
                  >
                    {message.content}
                  </div>
                ))}
              </div>
            </ScrollArea>
            <CardFooter className="border-t p-3">
              <form onSubmit={handleSubmit} className="flex w-full gap-2">
                <Input
                  placeholder="Ask AVA anything about your files..."
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  className="flex-1"
                  autoComplete="off"
                />
                <Button type="submit" size="icon" disabled={!input.trim()}>
                  <Send className="h-4 w-4" />
                  <span className="sr-only">Send</span>
                </Button>
              </form>
            </CardFooter>
          </Card>
        </div>
      )}
    </div>
  )
}

// frontend/dashboard35/src/app/core/ava-assistant.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-ava-assistant',
  template: `
    <div class="fixed bottom-6 right-6 z-50 flex flex-col items-end gap-2">
      <button
        class="flex h-14 w-14 items-center justify-center rounded-full bg-gradient-to-tr from-primary to-lime-400 text-primary-foreground shadow-lg hover:scale-105 transition-transform animate-pulse-glow"
        (click)="toggleOpen()"
        aria-label="Open AVA Assistant"
        *ngIf="!isOpen"
      >
        <mat-icon class="text-2xl">smart_toy</mat-icon>
      </button>
      <div *ngIf="isOpen" [ngClass]="isExpanded ? 'w-[350px] h-[500px] md:w-[600px] md:h-[700px]' : 'w-[350px] h-[500px]'" class="flex flex-col bg-background rounded-lg border shadow-lg card-hover">
        <div class="flex items-center justify-between border-b px-4 py-3">
          <div class="flex items-center gap-2">
            <div class="flex h-8 w-8 items-center justify-center rounded-full bg-primary">
              <mat-icon class="text-primary-foreground">smart_toy</mat-icon>
            </div>
            <div>
              <span class="text-lg font-bold gradient-text">AVA</span>
              <div class="text-xs text-muted-foreground">Artifact Virtual Assistant</div>
            </div>
          </div>
          <div class="flex gap-1">
            <button mat-icon-button (click)="toggleExpand()" [attr.aria-label]="isExpanded ? 'Minimize' : 'Maximize'">
              <mat-icon>{{ isExpanded ? 'fullscreen_exit' : 'fullscreen' }}</mat-icon>
            </button>
            <button mat-icon-button (click)="toggleOpen()" aria-label="Close">
              <mat-icon>close</mat-icon>
            </button>
          </div>
        </div>
        <div class="flex-1 overflow-y-auto p-4">
          <div class="flex flex-col gap-4">
            <div *ngFor="let message of messages" [ngClass]="message.sender === 'user' ? 'ml-auto bg-primary text-primary-foreground' : 'bg-muted'" class="flex w-max max-w-[80%] flex-col gap-2 rounded-lg px-3 py-2 text-sm">
              {{ message.content }}
            </div>
          </div>
        </div>
        <form (ngSubmit)="handleSubmit()" class="flex w-full gap-2 border-t p-3">
          <input
            class="flex-1 rounded border px-3 py-2 text-sm bg-background focus:outline-none focus:ring-2 focus:ring-primary"
            placeholder="Ask AVA anything about Artifact Virtual..."
            [(ngModel)]="input"
            name="avaInput"
            autocomplete="off"
          />
          <button mat-icon-button type="submit" [disabled]="!input.trim()">
            <mat-icon>send</mat-icon>
          </button>
        </form>
      </div>
    </div>
  `,
  styleUrls: ['./ava-assistant.component.scss']
})
export class AvaAssistantComponent {
  isOpen = false;
  isExpanded = false;
  input = '';
  messages = [
    {
      id: 'welcome',
      content: "Hello! I'm AVA, Artifact Virtual's Assistant. How can I help you?",
      sender: 'assistant',
      timestamp: new Date(),
    },
  ];

  toggleOpen() {
    this.isOpen = !this.isOpen;
  }
  toggleExpand() {
    this.isExpanded = !this.isExpanded;
  }
  handleSubmit() {
    if (this.input.trim()) {
      this.messages.push({
        id: `user-${Date.now()}`,
        content: this.input,
        sender: 'user',
        timestamp: new Date(),
      });
      this.input = '';
      setTimeout(() => {
        this.messages.push({
          id: `assistant-${Date.now()}`,
          content: "I'm AVA, your virtual assistant. I can help you navigate Artifact Virtual, manage projects, and answer questions about AI, blockchain, and quantum computing.",
          sender: 'assistant',
          timestamp: new Date(),
        });
      }, 1000);
    }
  }
}
