// frontend/dashboard32/components/header.tsx
"use client"

import { Button } from "@/components/ui/button"
import { ModeToggle } from "@/components/mode-toggle"
import { Bell, Search } from "lucide-react"
import { Input } from "@/components/ui/input"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import { SidebarTrigger } from "@/components/ui/sidebar"
import { Logo } from "@/components/ui/logo"

export function Header() {
  return (
    <header className="sticky top-0 z-30 flex h-16 items-center gap-4 border-b bg-background/80 backdrop-blur-md px-6">
      <div className="flex items-center gap-2 md:hidden">
        <SidebarTrigger />
      </div>

      <div className="md:hidden">
        <Logo size="sm" />
      </div>

      <div className="flex-1 md:flex md:justify-center">
        <div className="relative w-full max-w-lg">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <Input
            type="search"
            placeholder="Search across files, projects, and knowledge..."
            className="w-full bg-background/50 pl-10 pr-4 focus:bg-background"
          />
        </div>
      </div>

      <div className="flex items-center gap-2">
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="outline" size="icon" className="relative">
              <Bell className="h-5 w-5" />
              <span className="absolute -top-1 -right-1 flex h-4 w-4 items-center justify-center rounded-full bg-primary text-primary-foreground text-[10px] font-bold">
                3
              </span>
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuLabel>Notifications</DropdownMenuLabel>
            <DropdownMenuSeparator />
            <DropdownMenuItem>
              <span className="font-medium mr-2">📊</span> System update completed
            </DropdownMenuItem>
            <DropdownMenuItem>
              <span className="font-medium mr-2">🔄</span> Model quantization finished
            </DropdownMenuItem>
            <DropdownMenuItem>
              <span className="font-medium mr-2">📚</span> 2 new documents added to library
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>

        <ModeToggle />
      </div>
    </header>
  )
}

// frontend/dashboard35/src/app/core/header.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-header',
  template: `
    <header class="sticky top-0 z-30 flex h-16 items-center gap-4 border-b bg-background/90 backdrop-blur-lg px-6 shadow-sm">
      <div class="flex items-center gap-2 md:hidden">
        <button mat-icon-button aria-label="Open sidebar">
          <mat-icon>menu</mat-icon>
        </button>
      </div>
      <div class="md:hidden">
        <span class="font-bold gradient-text text-xl">Artifact</span>
      </div>
      <div class="flex-1 md:flex md:justify-center">
        <div class="relative w-full max-w-lg">
          <mat-icon class="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">search</mat-icon>
          <input type="search" placeholder="Search across files, projects, and knowledge..." class="w-full bg-background/50 pl-10 pr-4 focus:bg-background rounded-md border-muted/40 h-10" />
        </div>
      </div>
      <div class="flex items-center gap-3">
        <button mat-icon-button aria-label="Notifications">
          <mat-icon>notifications</mat-icon>
        </button>
        <button mat-icon-button aria-label="User menu">
          <mat-icon>account_circle</mat-icon>
        </button>
      </div>
    </header>
  `,
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent {}
