// frontend/dashboard35/src/app/ava-assistant/ava-assistant.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-ava-assistant',
  template: `
    <div class="ava-assistant" role="complementary" aria-label="AVA Assistant">
      <button class="ava-toggle" (click)="toggleOpen()" *ngIf="!isOpen" aria-label="Open AVA Assistant">
        🤖
      </button>
      <div *ngIf="isOpen" class="ava-chat" [class.expanded]="isExpanded">
        <div class="ava-header">
          <span class="ava-title">AVA</span>
          <button class="ava-expand" (click)="toggleExpand()" aria-label="Expand/Minimize">
            {{ isExpanded ? '🗕' : '🗖' }}
          </button>
          <button class="ava-close" (click)="toggleOpen()" aria-label="Close AVA Assistant">✖️</button>
        </div>
        <div class="ava-messages">
          <div *ngFor="let msg of messages" [ngClass]="{'ava-user': msg.sender==='user', 'ava-assistant-msg': msg.sender==='assistant'}" class="ava-message">
            {{ msg.content }}
          </div>
        </div>
        <form class="ava-form" (ngSubmit)="sendMessage()">
          <input [(ngModel)]="input" name="avaInput" class="ava-input" placeholder="Ask AVA anything..." autocomplete="off" required />
          <button type="submit" class="ava-send" [disabled]="!input.trim()">➤</button>
        </form>
      </div>
    </div>
  `,
  styles: [`
    .ava-assistant {
      position: fixed;
      bottom: 2rem;
      right: 2rem;
      z-index: var(--ava-z);
      background: var(--color-card);
      color: var(--color-card-foreground);
      border-radius: 1rem;
      box-shadow: 0 4px 24px rgba(0,0,0,0.12);
      min-width: 300px;
      transition: background var(--transition), color var(--transition);
      display: flex;
      flex-direction: column;
      align-items: flex-end;
    }
    .ava-toggle {
      font-size: 2rem;
      background: var(--color-primary);
      color: var(--color-primary-foreground);
      border: none;
      border-radius: 50%;
      width: 3.5rem;
      height: 3.5rem;
      box-shadow: 0 2px 8px rgba(0,0,0,0.12);
      cursor: pointer;
      margin-bottom: 0.5rem;
      transition: background var(--transition), color var(--transition);
    }
    .ava-chat {
      width: 350px;
      height: 500px;
      background: var(--color-card);
      color: var(--color-card-foreground);
      border-radius: 1rem;
      box-shadow: 0 4px 24px rgba(0,0,0,0.12);
      display: flex;
      flex-direction: column;
      overflow: hidden;
      transition: width 0.2s, height 0.2s;
    }
    .ava-chat.expanded {
      width: 600px;
      height: 90vh;
      right: 2rem;
      left: 2rem;
      top: 2rem;
      bottom: 2rem;
      position: fixed;
    }
    .ava-header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 1rem;
      background: var(--color-primary);
      color: var(--color-primary-foreground);
      border-bottom: 1px solid var(--color-border);
    }
    .ava-title {
      font-weight: 700;
      font-size: 1.1rem;
    }
    .ava-expand, .ava-close {
      background: none;
      border: none;
      font-size: 1.2rem;
      margin-left: 0.5rem;
      cursor: pointer;
      color: inherit;
    }
    .ava-messages {
      flex: 1;
      padding: 1rem;
      overflow-y: auto;
      background: var(--color-card);
      color: var(--color-card-foreground);
      display: flex;
      flex-direction: column;
      gap: 0.5rem;
    }
    .ava-message {
      padding: 0.5rem 1rem;
      border-radius: var(--radius);
      max-width: 80%;
      word-break: break-word;
      font-size: 0.98rem;
    }
    .ava-user {
      align-self: flex-end;
      background: var(--color-primary);
      color: var(--color-primary-foreground);
    }
    .ava-assistant-msg {
      align-self: flex-start;
      background: var(--color-muted);
      color: var(--color-muted-foreground);
    }
    .ava-form {
      display: flex;
      gap: 0.5rem;
      padding: 1rem;
      border-top: 1px solid var(--color-border);
      background: var(--color-card);
    }
    .ava-input {
      flex: 1;
      padding: 0.5rem 1rem;
      border-radius: var(--radius);
      border: 1px solid var(--color-border);
      font-size: 1rem;
      background: var(--color-muted);
      color: var(--color-foreground);
      transition: border var(--transition), background var(--transition);
    }
    .ava-send {
      background: var(--color-primary);
      color: var(--color-primary-foreground);
      border: none;
      border-radius: var(--radius);
      padding: 0 1rem;
      font-size: 1.2rem;
      cursor: pointer;
      transition: background var(--transition), color var(--transition);
    }
  `]
})
export class AvaAssistantComponent {
  isOpen = false;
  isExpanded = false;
  input = '';
  messages = [
    { sender: 'assistant', content: "Hello! I'm AVA, Artifact Virtual's Assistant. How can I help you?" }
  ];
  toggleOpen() { this.isOpen = !this.isOpen; }
  toggleExpand() { this.isExpanded = !this.isExpanded; }
  sendMessage() {
    if (this.input.trim()) {
      this.messages.push({ sender: 'user', content: this.input });
      setTimeout(() => {
        this.messages.push({ sender: 'assistant', content: "I'm AVA, your virtual assistant. I can help you navigate the Artifact Virtual platform, manage your projects, and answer questions about AI, blockchain, and quantum computing." });
      }, 800);
      this.input = '';
    }
  }
}

<!-- Main AVA Assistant Container -->
<div class="fixed bottom-4 right-4 z-50 flex flex-col items-end" role="complementary" aria-label="AVA Assistant">
  <!-- Floating Toggle Button -->
  <button
    *ngIf="!isOpen"
    (click)="toggleOpen()"
    aria-label="Open AVA Assistant"
    class="mb-2 flex h-14 w-14 items-center justify-center rounded-full bg-gradient-to-br from-teal-500 to-lime-500 text-white shadow-lg transition-all hover:from-teal-600 hover:to-lime-600 focus:outline-none focus:ring-2 focus:ring-lime-400 focus:ring-offset-2 focus:ring-offset-gray-800 animate-pulse-glow"
  >
    <!-- Bot Icon (Placeholder SVG - replace with actual icon) -->
    <svg class="h-7 w-7" fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 10h.01M12 10h.01M16 10h.01M9 16H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-5l-3 3-3-3z" />
    </svg>
  </button>

  <!-- Chat Interface -->
  <div
    *ngIf="isOpen"
    class="flex flex-col rounded-lg border border-gray-700 bg-gray-800 text-gray-100 shadow-xl transition-all duration-300 ease-in-out card-hover-glow"
    [ngClass]="{
      'fixed bottom-4 right-4 top-4 left-4 md:left-auto md:w-[600px]': isExpanded,
      'w-[380px] h-[550px]': !isExpanded
    }"
  >
    <!-- Chat Header -->
    <header class="flex items-center justify-between border-b border-gray-700 px-4 py-3">
      <div class="flex items-center gap-2">
        <div class="flex h-9 w-9 items-center justify-center rounded-full bg-gradient-to-br from-teal-500 to-lime-500 text-white">
          <!-- Bot Icon (Placeholder) -->
          <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 10h.01M12 10h.01M16 10h.01M9 16H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-5l-3 3-3-3z" /></svg>
        </div>
        <div>
          <h2 class="text-lg font-semibold bg-clip-text text-transparent bg-gradient-to-r from-teal-400 to-lime-400">AVA</h2>
          <p class="text-xs text-gray-400">Artifact Virtual Assistant</p>
        </div>
      </div>
      <div class="flex items-center gap-1">
        <button (click)="toggleExpand()" class="rounded-md p-1.5 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-gray-500" [attr.aria-label]="isExpanded ? 'Minimize chat' : 'Maximize chat'">
          <!-- Maximize/Minimize Icons (Placeholders) -->
          <svg *ngIf="!isExpanded" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 8V4m0 0h4M4 4l5 5m11-1v4m0 0h-4m4 0l-5-5M4 16v4m0 0h4m-4 0l5-5m11 5v-4m0 0h-4m4 0l-5 5" /></svg>
          <svg *ngIf="isExpanded" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7M9 5l7 7-7 7" /></svg> <!-- Simple minimize, replace with better icon -->
          <span class="sr-only">{{ isExpanded ? 'Minimize' : 'Maximize' }}</span>
        </button>
        <button (click)="toggleOpen()" class="rounded-md p-1.5 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-gray-500" aria-label="Close chat">
          <!-- Close Icon (Placeholder) -->
          <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" /></svg>
          <span class="sr-only">Close</span>
        </button>
      </div>
    </header>

    <!-- Messages Area -->
    <section #scrollMe class="flex-1 overflow-y-auto p-4 space-y-3 custom-scrollbar">
      <div *ngFor="let msg of messages" class="flex"
        [ngClass]="{
          'justify-end': msg.sender === 'user',
          'justify-start': msg.sender === 'assistant'
        }">
        <div class="max-w-[80%] rounded-xl px-3.5 py-2.5 text-sm shadow-md"
          [ngClass]="{
            'bg-gradient-to-br from-teal-500 to-lime-500 text-white': msg.sender === 'user',
            'bg-gray-700 text-gray-200': msg.sender === 'assistant'
          }">
          <p class="whitespace-pre-wrap break-words">{{ msg.content }}</p>
          <p class="mt-1 text-xs opacity-70 text-right">{{ msg.timestamp | date:'shortTime' }}</p>
        </div>
      </div>
    </section>

    <!-- Input Form Footer -->
    <footer class="border-t border-gray-700 p-3">
      <form (ngSubmit)="sendMessage()" class="flex w-full items-center gap-2">
        <input
          [(ngModel)]="input"
          name="avaInput"
          placeholder="Ask AVA anything..."
          autocomplete="off"
          required
          class="flex-1 rounded-md border-gray-600 bg-gray-700 px-4 py-2.5 text-sm placeholder-gray-400 focus:border-teal-500 focus:bg-gray-900 focus:text-white focus:outline-none focus:ring-1 focus:ring-teal-500"
        />
        <button
          type="submit"
          [disabled]="!input.trim()"
          class="flex h-10 w-10 items-center justify-center rounded-full bg-gradient-to-br from-teal-500 to-lime-500 text-white shadow-md transition-opacity hover:opacity-90 focus:outline-none focus:ring-2 focus:ring-lime-400 focus:ring-offset-2 focus:ring-offset-gray-800 disabled:opacity-50"
          aria-label="Send message"
        >
          <!-- Send Icon (Placeholder) -->
          <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" /></svg>
          <span class="sr-only">Send</span>
        </button>
      </form>
    </footer>
  </div>
</div>

// frontend/dashboard34/components/ava-assistant.tsx
"use client"

import type * as React from "react"
import { useState } from "react"
import { Bot, Maximize2, Minimize2, Send, X } from "lucide-react"

import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Card, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { ScrollArea } from "@/components/ui/scroll-area"
import { cn } from "@/lib/utils"

interface AvaAssistantProps {
  className?: string
}

type Message = {
  id: string
  content: string
  sender: "user" | "assistant"
  timestamp: Date
}

export function AvaAssistant({ className }: AvaAssistantProps) {
  const [isOpen, setIsOpen] = useState(false)
  const [isExpanded, setIsExpanded] = useState(false)
  const [input, setInput] = useState("")
  const [messages, setMessages] = useState<Message[]>([
    {
      id: "welcome",
      content: "Hello! I'm AVA, Artifact Virtual's Assistant. How can I help you?",
      sender: "assistant",
      timestamp: new Date(),
    },
  ])

  const toggleOpen = () => setIsOpen(!isOpen)
  const toggleExpand = () => setIsExpanded(!isExpanded)

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault()

    if (input.trim()) {
      // Add user message
      const userMessage: Message = {
        id: `user-${Date.now()}`,
        content: input,
        sender: "user",
        timestamp: new Date(),
      }

      setMessages((prev) => [...prev, userMessage])
      setInput("")

      // Simulate assistant response (in a real app, you'd call your LLM API here)
      setTimeout(() => {
        const assistantMessage: Message = {
          id: `assistant-${Date.now()}`,
          content:
            "I'm AVA, your virtual assistant. I can help you navigate the Artifact Virtual platform, manage your projects, and answer questions about AI, blockchain, and quantum computing.",
          sender: "assistant",
          timestamp: new Date(),
        }
        setMessages((prev) => [...prev, assistantMessage])
      }, 1000)
    }
  }

  return (
    <div className={cn("fixed bottom-4 right-4 z-50", className)}>
      {/* Floating Button */}
      {!isOpen && (
        <button
          className="flex h-14 w-14 items-center justify-center rounded-full bg-primary text-primary-foreground shadow-lg hover:bg-primary/90 animate-pulse-glow"
          onClick={toggleOpen}
        >
          <Bot className="h-6 w-6" />
        </button>
      )}

      {/* Chat Interface */}
      {isOpen && (
        <div
          className={cn(
            "flex flex-col bg-background rounded-lg border shadow-lg card-hover",
            isExpanded ? "fixed bottom-4 right-4 top-4 left-4 md:left-auto md:w-[600px]" : "w-[350px] h-[500px]",
          )}
        >
          <Card className="flex flex-col h-full border-0 rounded-lg">
            <CardHeader className="border-b px-4 py-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary">
                    <Bot className="h-4 w-4 text-primary-foreground" />
                  </div>
                  <div>
                    <CardTitle className="text-lg gradient-text">AVA</CardTitle>
                    <CardDescription className="text-xs">Artifact Virtual Assistant</CardDescription>
                  </div>
                </div>
                <div className="flex gap-1">
                  <Button variant="ghost" size="icon" className="h-8 w-8" onClick={toggleExpand}>
                    {isExpanded ? <Minimize2 className="h-4 w-4" /> : <Maximize2 className="h-4 w-4" />}
                    <span className="sr-only">{isExpanded ? "Minimize" : "Maximize"}</span>
                  </Button>
                  <Button variant="ghost" size="icon" className="h-8 w-8" onClick={toggleOpen}>
                    <X className="h-4 w-4" />
                    <span className="sr-only">Close</span>
                  </Button>
                </div>
              </div>
            </CardHeader>
            <ScrollArea className="flex-1 p-4">
              <div className="flex flex-col gap-4">
                {messages.map((message) => (
                  <div
                    key={message.id}
                    className={cn(
                      "flex w-max max-w-[80%] flex-col gap-2 rounded-lg px-3 py-2 text-sm",
                      message.sender === "user" ? "ml-auto bg-primary text-primary-foreground" : "bg-muted",
                    )}
                  >
                    {message.content}
                  </div>
                ))}
              </div>
            </ScrollArea>
            <CardFooter className="border-t p-3">
              <form onSubmit={handleSubmit} className="flex w-full gap-2">
                <Input
                  placeholder="Ask AVA anything about your files..."
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  className="flex-1"
                  autoComplete="off"
                />
                <Button type="submit" size="icon" disabled={!input.trim()}>
                  <Send className="h-4 w-4" />
                  <span className="sr-only">Send</span>
                </Button>
              </form>
            </CardFooter>
          </Card>
        </div>
      )}
    </div>
  )
}
