// frontend/dashboard35/src/app/core/sidebar.component.ts
import { Component } from '@angular/core';

interface SidebarNavItem {
  title: string;
  icon: string;
  route?: string;
  children?: SidebarNavItem[];
  badge?: string;
}

@Component({
  selector: 'app-sidebar',
  template: `
    <aside class="fixed inset-y-0 left-0 z-40 w-64 bg-background border-r border-border flex flex-col transition-transform duration-200 ease-in-out md:static md:translate-x-0">
      <div class="flex h-16 items-center border-b px-6">
        <span class="font-bold gradient-text text-lg">Artifact Virtual</span>
      </div>
      <div class="flex-1 overflow-auto py-2 custom-scrollbar">
        <nav class="grid gap-2 px-2">
          <ng-container *ngFor="let group of navGroups">
            <div class="text-xs font-semibold text-muted-foreground mt-4 mb-2 px-2 uppercase tracking-wider">{{ group.title }}</div>
            <ng-container *ngFor="let item of group.items">
              <div *ngIf="!item.children" class="flex items-center gap-3 rounded-lg px-3 py-2 text-sm font-medium hover:bg-gradient-to-r hover:from-primary hover:to-lime-400 hover:text-primary-foreground transition-colors cursor-pointer" [routerLink]="item.route" routerLinkActive="bg-gradient-to-r from-primary to-lime-400 text-primary-foreground">
                <mat-icon>{{item.icon}}</mat-icon>
                <span>{{item.title}}</span>
                <span *ngIf="item.badge" class="ml-auto text-xs bg-lime-400 text-black rounded px-2 py-0.5">{{item.badge}}</span>
              </div>
              <div *ngIf="item.children" class="flex flex-col">
                <div class="flex items-center gap-3 rounded-lg px-3 py-2 text-sm font-medium hover:bg-gradient-to-r hover:from-primary hover:to-lime-400 hover:text-primary-foreground transition-colors cursor-pointer">
                  <mat-icon>{{item.icon}}</mat-icon>
                  <span>{{item.title}}</span>
                  <mat-icon class="ml-auto">expand_more</mat-icon>
                </div>
                <div class="ml-6 mt-1 flex flex-col gap-1">
                  <div *ngFor="let child of item.children" class="flex items-center gap-2 rounded px-2 py-1 text-xs font-medium hover:bg-gradient-to-r hover:from-primary hover:to-lime-400 hover:text-primary-foreground transition-colors cursor-pointer" [routerLink]="child.route" routerLinkActive="bg-gradient-to-r from-primary to-lime-400 text-primary-foreground">
                    <mat-icon>{{child.icon}}</mat-icon>
                    <span>{{child.title}}</span>
                    <span *ngIf="child.badge" class="ml-auto text-xs bg-lime-400 text-black rounded px-2 py-0.5">{{child.badge}}</span>
                  </div>
                </div>
              </div>
            </ng-container>
          </ng-container>
        </nav>
      </div>
      <div class="border-t p-4">
        <div class="flex items-center gap-3 rounded-lg bg-secondary p-3 text-sm">
          <div class="flex h-9 w-9 items-center justify-center rounded-full bg-primary text-primary-foreground">
            <mat-icon>terminal</mat-icon>
          </div>
          <div>
            <p class="font-medium">System Status</p>
            <p class="text-xs text-muted-foreground">Operational</p>
          </div>
        </div>
      </div>
    </aside>
  `,
  styleUrls: ['./sidebar.component.scss']
})
export class SidebarComponent {
  navGroups = [
    {
      title: 'Overview',
      items: [
        { title: 'Dashboard', icon: 'home', route: '/' },
      ],
    },
    {
      title: 'AI & Knowledge',
      items: [
        { title: 'AI Ecosystems', icon: 'psychology', route: '/ai-ecosystems', children: [
          { title: 'Overview', icon: 'dashboard', route: '/ai-ecosystems' },
          { title: 'AI Lab', icon: 'science', route: '/ai-ecosystems/lab', badge: 'New' },
          { title: 'Models', icon: 'memory', route: '/ai-ecosystems/models' },
          { title: 'Quantization', icon: 'tune', route: '/ai-ecosystems/quantization' },
          { title: 'Protocols', icon: 'hub', route: '/ai-ecosystems/protocols' },
        ]},
        { title: 'Knowledge', icon: 'menu_book', route: '/knowledge' },
      ],
    },
    {
      title: 'Blockchain & Systems',
      items: [
        { title: 'Blockchain', icon: 'hub', route: '/blockchain', children: [
          { title: 'Overview', icon: 'dashboard', route: '/blockchain' },
          { title: 'Wallets', icon: 'account_balance_wallet', route: '/blockchain/wallets' },
          { title: 'Smart Contracts', icon: 'code', route: '/blockchain/contracts' },
        ]},
        { title: 'System', icon: 'settings', route: '/system' },
        { title: 'Servers', icon: 'dns', route: '/servers' },
        { title: 'Quantum', icon: 'auto_awesome', route: '/quantum', badge: 'Beta' },
      ],
    },
    {
      title: 'Applications',
      items: [
        { title: 'Applications', icon: 'apps', route: '/applications', children: [
          { title: 'Meteor Editor', icon: 'cloud', route: '/applications/meteor' },
          { title: 'Oracle CLI', icon: 'terminal', route: '/applications/oracle' },
          { title: 'Temporal Calendar', icon: 'calendar_today', route: '/applications/calendar' },
        ]},
        { title: 'Research', icon: 'science', route: '/research', badge: '3' },
        { title: 'Projects', icon: 'layers', route: '/projects' },
      ],
    },
  ];
}

// frontend/dashboard32/components/sidebar.tsx
"use client"

import { cn } from "@/lib/utils"
import {
  Activity,
  Blocks,
  BookOpen,
  Brain,
  Calendar,
  Code,
  Database,
  FileCode,
  FileText,
  Home,
  LayoutDashboard,
  Settings,
  Terminal,
  Wrench,
} from "lucide-react"
import Link from "next/link"
import { usePathname } from "next/navigation"

interface SidebarProps {
  open: boolean
  onOpenChange: (open: boolean) => void
}

export function Sidebar({ open, onOpenChange }: SidebarProps) {
  const pathname = usePathname()

  const routes = [
    {
      title: "Dashboard",
      href: "/",
      icon: <Home className="h-5 w-5" />,
    },
    {
      title: "Projects",
      href: "/projects",
      icon: <LayoutDashboard className="h-5 w-5" />,
    },
    {
      title: "AI Ecosystems",
      href: "/ai-ecosystems",
      icon: <Brain className="h-5 w-5" />,
      children: [
        {
          title: "Models",
          href: "/ai-ecosystems/models",
          icon: <Blocks className="h-4 w-4" />,
        },
        {
          title: "AutoRound",
          href: "/ai-ecosystems/auto-round",
          icon: <Activity className="h-4 w-4" />,
        },
        {
          title: "MCP",
          href: "/ai-ecosystems/mcp",
          icon: <Terminal className="h-4 w-4" />,
        },
      ],
    },
    {
      title: "Knowledge Foundations",
      href: "/knowledge",
      icon: <BookOpen className="h-5 w-5" />,
      children: [
        {
          title: "Datasets",
          href: "/knowledge/datasets",
          icon: <Database className="h-4 w-4" />,
        },
        {
          title: "Library",
          href: "/knowledge/library",
          icon: <FileText className="h-4 w-4" />,
        },
      ],
    },
    {
      title: "Blockchain",
      href: "/blockchain",
      icon: <Code className="h-5 w-5" />,
      children: [
        {
          title: "Hardhat",
          href: "/blockchain/hardhat",
          icon: <Wrench className="h-4 w-4" />,
        },
        {
          title: "Smart Contracts",
          href: "/blockchain/contracts",
          icon: <FileCode className="h-4 w-4" />,
        },
      ],
    },
    {
      title: "Applications",
      href: "/applications",
      icon: <Terminal className="h-5 w-5" />,
      children: [
        {
          title: "Meteor Editor",
          href: "/applications/meteor",
          icon: <FileText className="h-4 w-4" />,
        },
        {
          title: "Oracle CLI",
          href: "/applications/oracle",
          icon: <Terminal className="h-4 w-4" />,
        },
        {
          title: "Temporal Calendar",
          href: "/applications/calendar",
          icon: <Calendar className="h-4 w-4" />,
        },
      ],
    },
    {
      title: "Settings",
      href: "/settings",
      icon: <Settings className="h-5 w-5" />,
    },
  ]

  return (
    <div
      className={cn(
        "fixed inset-y-0 left-0 z-50 flex w-64 flex-col border-r bg-background transition-transform lg:static lg:translate-x-0",
        open ? "translate-x-0" : "-translate-x-full",
      )}
    >
      <div className="flex h-16 items-center border-b px-6">
        <Link href="/" className="flex items-center gap-2 font-semibold">
          <Blocks className="h-6 w-6" />
          <span className="text-lg font-bold">Artifact Virtual</span>
        </Link>
      </div>
      <div className="flex-1 overflow-auto py-2">
        <nav className="grid gap-1 px-2">
          {routes.map((route, i) => (
            <div key={i}>
              <Link
                href={route.href}
                className={cn(
                  "flex items-center gap-3 rounded-lg px-3 py-2 text-sm font-medium hover:bg-accent hover:text-accent-foreground",
                  pathname === route.href ? "bg-accent text-accent-foreground" : "transparent",
                )}
              >
                {route.icon}
                {route.title}
              </Link>
              {route.children && (
                <div className="ml-4 mt-1 grid gap-1">
                  {route.children.map((child, j) => (
                    <Link
                      key={j}
                      href={child.href}
                      className={cn(
                        "flex items-center gap-3 rounded-lg px-3 py-2 text-sm font-medium hover:bg-accent hover:text-accent-foreground",
                        pathname === child.href ? "bg-accent text-accent-foreground" : "transparent",
                      )}
                    >
                      {child.icon}
                      {child.title}
                    </Link>
                  ))}
                </div>
              )}
            </div>
          ))}
        </nav>
      </div>
      <div className="border-t p-4">
        <div className="flex items-center gap-3 rounded-lg bg-secondary p-3 text-sm">
          <div className="flex h-9 w-9 items-center justify-center rounded-full bg-primary text-primary-foreground">
            <Terminal className="h-4 w-4" />
          </div>
          <div>
            <p className="font-medium">System Status</p>
            <p className="text-xs text-muted-foreground">Operational</p>
          </div>
        </div>
      </div>
    </div>
  )
}
